# Generated by Django 2.1 on 2018-11-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=' ', help_text='Enter a comment', max_length=1000)),
                ('date_of_public', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default=' ', help_text='Enter a content', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter a title', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
