# Generated by Django 2.1 on 2018-11-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181101_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
