# Generated by Django 2.1 on 2018-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181106_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
