# Generated by Django 2.1 on 2018-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181106_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_public',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
